/**
 * Human-authored PYAE Revision 3 evidence for Weeks 09-16.
 *
 * Data only: importing this module has no filesystem, learner-state, catalog,
 * compilation, or publication side effects. Resource destinations were
 * inspected on 2026-09-09.
 */

const checkedAt = '2026-09-09';

const judgment = (
  beginnerClarity,
  competencyFit,
  factualCorrectness,
  currency,
  stageAppropriateness,
  guidedPractice,
  accessibility,
) => ({
  beginnerClarity,
  competencyFit,
  factualCorrectness,
  currency,
  stageAppropriateness,
  guidedPractice,
  accessibility,
});

const candidate = (title, url, decision, evidence) => ({ title, url, decision, evidence });

function makeResourcePlan({
  weekId,
  decision,
  title,
  url,
  provider,
  format,
  estimatedMinutes,
  location,
  competencyIds,
  role,
  learningRole,
  purposes,
  assignmentPurpose,
  whySelected,
  formatRationale,
  alternativeNotes,
  candidateComparisons,
  judgment: resourceJudgment,
  rationale,
}) {
  const resourcePatch = {
    title,
    url,
    provider,
    format,
    cost: 'free',
    estimatedMinutes,
    location: { note: location },
    competencyIds,
    whySelected,
    accessStatus: 'verified',
    checkedAt,
    selectionRole: role,
    learningRole,
    formatRationale,
    purpose: purposes,
    evaluation: {
      competencyFit: resourceJudgment.competencyFit,
      clarity: resourceJudgment.beginnerClarity,
      correctnessAndCurrency:
        `${resourceJudgment.factualCorrectness} ${resourceJudgment.currency}`,
      accessibility: resourceJudgment.accessibility,
    },
    accessNotes:
      'The destination and assigned sections opened publicly on 2026-09-09; no payment or learner account is required.',
    alternativeNotes,
  };

  return {
    weekId,
    decision,
    resourcePatch,
    assignment: {
      role,
      learningRole,
      competencyIds,
      purpose: assignmentPurpose,
    },
    candidateComparisons,
    judgment: resourceJudgment,
    rationale,
  };
}

function makeAddedResourcePlan(id, spec) {
  const plan = makeResourcePlan(spec);
  return {
    weekId: plan.weekId,
    resource: { id, ...plan.resourcePatch },
    assignment: plan.assignment,
    candidateComparisons: plan.candidateComparisons,
    judgment: plan.judgment,
    rationale: plan.rationale,
  };
}

const officialJudgment = (fit, practice) => judgment(
  'The bounded assignment introduces terms before asking the learner to apply them.',
  fit,
  'The assigned behavior was checked against the primary source and avoids unsupported claims.',
  'The live destination and named sections were inspected on 2026-09-09.',
  'The scope is limited to what a motivated beginner needs in this week.',
  practice,
  'Free public material; no account, payment, or live model call is required.',
);

export const resourcePlans = {
  'PYAE-R-W09-01': makeResourcePlan({
    weekId: 'PYAE-W09', decision: 'replace',
    title: 'typing.Protocol and @runtime_checkable',
    url: 'https://docs.python.org/3/library/typing.html#typing.Protocol',
    provider: 'Python Software Foundation', format: 'documentation', estimatedMinutes: 45,
    location: 'Read typing.Protocol through @typing.runtime_checkable. Type and run a ModelGateway/FakeModel example, then explain why runtime checks inspect member presence rather than full signatures.',
    competencyIds: ['PYAE-C014', 'PYAE-C016'], role: 'core', learningRole: 'learn',
    purposes: ['primary mental model', 'structural interface reference'],
    assignmentPurpose: 'Learn how a provider implementation can satisfy the app-owned model interface by shape, without inheriting from a vendor or shared base class.',
    whySelected: 'This exact official section teaches structural subtyping and its runtime limitation with executable Python examples; it directly repairs the R2 OpenAI-quickstart mismatch.',
    formatRationale: 'A bounded language reference plus a tiny typed example is precise enough to teach this interface boundary.',
    alternativeNotes: 'The typing specification was accurate but substantially more advanced; the existing OpenAI quickstart did not teach Protocol at all.',
    candidateComparisons: [
      candidate('OpenAI API Quickstart', 'https://developers.openai.com/api/docs/quickstart', 'rejected', 'Provider setup does not teach structural subtyping.'),
      candidate('Protocols and structural subtyping', 'https://typing.python.org/en/latest/spec/protocol.html', 'not selected', 'Normative but too dense for the first encounter.'),
    ],
    judgment: officialJudgment('Directly teaches Protocol, structural conformance, and runtime_checkable for C014/C016.', 'The learner types and tests a minimal gateway and fake.'),
    rationale: 'Replace the severe metadata/content mismatch while preserving the curricular resource slot ID.',
  }),
  'PYAE-R-W09-02': makeResourcePlan({
    weekId: 'PYAE-W09', decision: 'retain-repair',
    title: 'Generate a chat message - Ollama', url: 'https://docs.ollama.com/api/chat',
    provider: 'Ollama', format: 'documentation', estimatedMinutes: 30,
    location: 'Inspect the POST example and the model, messages, and stream fields; then inspect response message, done_reason, and token counts. Sketch the app-owned mapping. Running Ollama is optional.',
    competencyIds: ['PYAE-C016'], role: 'core', learningRole: 'reference',
    purposes: ['local provider reference', 'message-boundary mapping'],
    assignmentPurpose: 'See one concrete local chat contract and map its provider fields into ChatMessage and ModelResponse without coupling the core to Ollama.',
    whySelected: 'The exact chat endpoint shows both request and response shapes for a free local provider and supports the optional adapter without turning provider execution into an assessed requirement.',
    formatRationale: 'An endpoint reference is appropriate after the app-owned boundary has been taught.',
    alternativeNotes: 'The prior Ollama introduction page was too shallow; this repairs the title, URL, purpose, and core assignment.',
    candidateComparisons: [candidate('Introduction - Ollama', 'https://docs.ollama.com/api/introduction', 'rejected', 'Too general to support the required request/response mapping.')],
    judgment: officialJudgment('Supports the provider-neutral request/response model in C016.', 'The learner annotates an actual payload and maps only the needed fields.'),
    rationale: 'Retain the local-provider learning function but point it to the exact API page.',
  }),
  'PYAE-R-W09-03': makeResourcePlan({
    weekId: 'PYAE-W09', decision: 'replace-promote',
    title: 'unittest.mock - Quick Guide', url: 'https://docs.python.org/3/library/unittest.mock.html',
    provider: 'Python Software Foundation', format: 'documentation', estimatedMinutes: 45,
    location: 'Read the introduction and Quick Guide through iterable side_effect and call assertions. Then implement a hand-written ScriptedModel response queue and calls list; do not use Mock as the final FakeModel.',
    competencyIds: ['PYAE-C011', 'PYAE-C016'], role: 'core', learningRole: 'practice',
    purposes: ['test-double practice', 'deterministic call inspection'],
    assignmentPurpose: 'Practice deterministic responses and call recording before implementing the project FakeModel as a small transparent test double.',
    whySelected: 'The official quick guide demonstrates response scripting and call assertions in runnable Python, the two exact behaviors the Build requires.',
    formatRationale: 'A short code-along turns test-double vocabulary into observable behavior.',
    alternativeNotes: 'The generic cookbook examples were unfocused; Fowler offers useful taxonomy but is longer and Java-centered.',
    candidateComparisons: [
      candidate('Mocks Aren\'t Stubs', 'https://martinfowler.com/articles/mocksArentStubs.html', 'not selected', 'Strong taxonomy but too long and Java-oriented for this implementation need.'),
      candidate('OpenAI Cookbook examples', 'https://cookbook.openai.com/', 'rejected', 'Provider examples do not directly teach this hand-written fake contract.'),
    ],
    judgment: officialJudgment('Directly supports deterministic FakeModel behavior, C011, and C016.', 'The learner recreates the relevant mechanics in a simple explicit fake.'),
    rationale: 'Promote deterministic test-double practice into Core because the Build and Skill Check depend on it.',
  }),

  'PYAE-R-W10-01': makeResourcePlan({
    weekId: 'PYAE-W10', decision: 'retain-repair', title: 'Text generation',
    url: 'https://developers.openai.com/api/docs/guides/text', provider: 'OpenAI', format: 'documentation', estimatedMinutes: 50,
    location: 'Read instructions, message roles, and prompt examples. Rewrite one extraction request into task, context, constraints, schema, and example sections. Do not make an API call.',
    competencyIds: ['PYAE-C017'], role: 'core', learningRole: 'learn', purposes: ['prompt-contract explanation', 'worked decomposition'],
    assignmentPurpose: 'Learn to turn an underspecified extraction request into a bounded contract whose instructions and input are visibly separated.',
    whySelected: 'The guide provides current concrete message/instruction examples that can be studied offline and adapted into the Build prompt boundary.',
    formatRationale: 'Worked provider examples are used for prompt structure, not provider adoption.',
    alternativeNotes: 'Retained with an exact offline activity and stop boundary.',
    candidateComparisons: [candidate('Prompt engineering guide', 'https://platform.openai.com/docs/guides/prompt-engineering', 'not selected', 'Broader and less directly tied to the current text-generation contract.')],
    judgment: officialJudgment('Directly supports prompt-contract design in C017.', 'The learner repairs a concrete extraction prompt.'), rationale: 'Retain as the week\'s bounded prompt-design lesson.',
  }),
  'PYAE-R-W10-02': makeResourcePlan({
    weekId: 'PYAE-W10', decision: 'retain-repair', title: 'Structured model outputs',
    url: 'https://developers.openai.com/api/docs/guides/structured-outputs', provider: 'OpenAI', format: 'documentation', estimatedMinutes: 60,
    location: 'Read the introduction, JSON Schema and Pydantic examples, strict mode, refusals, and incomplete responses. Stop before advanced examples and other languages; no API execution is required.',
    competencyIds: ['PYAE-C018'], role: 'core', learningRole: 'learn', purposes: ['structured-output model', 'failure-boundary explanation'],
    assignmentPurpose: 'Understand what schema-constrained model output can guarantee and which refusal or incomplete-result states application code must still handle.',
    whySelected: 'The page explains current structured-output behavior and its explicit failure cases, preventing the false assumption that JSON-shaped output always satisfies application rules.',
    formatRationale: 'The provider reference is the primary source for the feature semantics being compared with local validation.',
    alternativeNotes: 'Execution is excluded so the assessed path remains offline.',
    candidateComparisons: [candidate('JSON mode', 'https://developers.openai.com/api/docs/guides/structured-outputs#json-mode', 'not selected alone', 'Narrower and weaker than the full structured-output plus failure-state explanation.')],
    judgment: officialJudgment('Directly supports schema constraints and failure handling in C018.', 'The learner classifies sample outputs as valid, refusal, incomplete, or schema-invalid.'), rationale: 'Retain with explicit scope and offline use.',
  }),
  'PYAE-R-W10-03': makeResourcePlan({
    weekId: 'PYAE-W10', decision: 'replace', title: 'JSON - Pydantic Validation',
    url: 'https://docs.pydantic.dev/latest/concepts/json/', provider: 'Pydantic', format: 'documentation', estimatedMinutes: 45,
    location: 'Read JSON Parsing through the first model_validate_json and ValidationError example. Stop before Partial JSON Parsing. Run valid, malformed, and schema-invalid TaskExtraction inputs locally.',
    competencyIds: ['PYAE-C017', 'PYAE-C018'], role: 'core', learningRole: 'practice', purposes: ['local validation practice', 'malformed-versus-invalid diagnosis'],
    assignmentPurpose: 'Run three local inputs to distinguish malformed JSON from valid JSON that violates your application schema.',
    whySelected: 'The official Pydantic page gives the exact offline parse/validate/error workflow used by the extraction engine without requiring a provider account.',
    formatRationale: 'A short executable documentation lab directly prepares the repair loop.',
    alternativeNotes: 'Selected over generic cookbook material and an API-dependent notebook.',
    candidateComparisons: [
      candidate('OpenAI Cookbook', 'https://cookbook.openai.com/', 'rejected', 'Too generic and provider-dependent for the local validation dependency.'),
      candidate('Structured Outputs Introduction', 'https://cookbook.openai.com/examples/structured_outputs_intro', 'not selected', 'Relevant but requires an API path that is unnecessary for the assessed Build.'),
    ],
    judgment: officialJudgment('Directly teaches local Pydantic JSON validation for C014/C018.', 'Three runnable cases expose both syntax and schema failures.'), rationale: 'Replace the generic example source with the exact offline validation prerequisite.',
  }),

  'PYAE-R-W11-01': makeResourcePlan({
    weekId: 'PYAE-W11', decision: 'retain-repair', title: 'Function calling', url: 'https://developers.openai.com/api/docs/guides/function-calling',
    provider: 'OpenAI', format: 'documentation', estimatedMinutes: 70,
    location: 'Read How it works, Defining functions, Handling function calls, Returning results, strict mode, and the first multiple-call example. Trace one complete request-call-dispatch-result-request cycle on paper.',
    competencyIds: ['PYAE-C018', 'PYAE-C019'], role: 'core', learningRole: 'learn', purposes: ['tool-call lifecycle', 'schema contract'],
    assignmentPurpose: 'Trace the complete boundary between the model selecting a tool and your application validating, executing, and returning its observation.',
    whySelected: 'The guide presents the complete tool-call loop and precise schema/call identifiers needed by the provider-neutral registry.',
    formatRationale: 'A traced primary-source lifecycle is clearer than isolated schema snippets.', alternativeNotes: 'Retained; the assignment stops before unrelated provider options.',
    candidateComparisons: [candidate('Tools - Agents SDK', 'https://openai.github.io/openai-agents-python/tools/', 'selected separately', 'Useful implementation comparison, but the function-calling guide explains the wire lifecycle more explicitly.')],
    judgment: officialJudgment('Directly teaches the lifecycle and identifiers required by C018/C019.', 'The paper trace forces active sequencing without a live model.'), rationale: 'Retain as the main lifecycle explanation.',
  }),
  'PYAE-R-W11-02': makeResourcePlan({
    weekId: 'PYAE-W11', decision: 'retain-repair', title: 'Tools in the OpenAI Agents SDK', url: 'https://openai.github.io/openai-agents-python/tools/',
    provider: 'OpenAI', format: 'documentation', estimatedMinutes: 45,
    location: 'Inspect Function tools, automatic schema generation from annotations/docstrings, and error handling. Compare the SDK convenience layer with the app-owned ToolRegistry; installation is not required.',
    competencyIds: ['PYAE-C019'], role: 'core', learningRole: 'reference', purposes: ['implementation comparison', 'schema-generation reference'],
    assignmentPurpose: 'Compare a maintained tool wrapper with your registry so you can identify what annotations, descriptions, validation, and error conversion must accomplish.',
    whySelected: 'The concise page shows how a production Python tool layer derives schemas and contains failures, while the assignment keeps framework ownership in the learner\'s code.',
    formatRationale: 'Used as a bounded reference after the lifecycle is taught.', alternativeNotes: 'No SDK installation or provider execution is needed.',
    candidateComparisons: [candidate('Function calling', 'https://developers.openai.com/api/docs/guides/function-calling', 'selected as primary', 'Better lifecycle explanation; this page supplies Python implementation comparison.')],
    judgment: officialJudgment('Supports schema generation and error containment in C019.', 'The learner produces a side-by-side mapping to the custom registry.'), rationale: 'Retain as reference, not architecture mandate.',
  }),
  'PYAE-R-W11-03': makeResourcePlan({
    weekId: 'PYAE-W11', decision: 'replace-promote', title: 'inspect.signature', url: 'https://docs.python.org/3/library/inspect.html#inspect.signature',
    provider: 'Python Software Foundation', format: 'documentation', estimatedMinutes: 55,
    location: 'Read the Signature section through Signature.bind. Inspect three annotated functions, print parameter names/annotations/defaults, bind valid and invalid arguments, and manually draft one JSON schema.',
    competencyIds: ['PYAE-C004', 'PYAE-C019'], role: 'core', learningRole: 'practice', purposes: ['reflection practice', 'argument-binding practice'],
    assignmentPurpose: 'Practice reading function signatures and binding incoming arguments before attempting automatic tool-schema generation.',
    whySelected: 'The standard-library source teaches the exact introspection and binding mechanics hidden inside the Build\'s stretch and dispatcher validation.',
    formatRationale: 'A small runnable inspection lab makes the API concrete.', alternativeNotes: 'Generic repositories were unfocused; an exact SDK example was unavailable during inspection.',
    candidateComparisons: [candidate('OpenAI Agents Python examples', 'https://github.com/openai/openai-agents-python/tree/main/examples', 'rejected', 'Repository-wide examples do not isolate inspect.signature and binding.')],
    judgment: officialJudgment('Directly supports function inspection and safe argument handling for C019.', 'The learner runs three inspections and one binding failure.'), rationale: 'Replace generic examples and make the previously hidden Build dependency Core.',
  }),

  'PYAE-R-W12-01': makeResourcePlan({
    weekId: 'PYAE-W12', decision: 'retain-repair', title: 'Conversation state', url: 'https://developers.openai.com/api/docs/guides/conversation-state',
    provider: 'OpenAI', format: 'documentation', estimatedMinutes: 45,
    location: 'Read manual conversation-state management and Managing the context window, including input/output/reasoning tokens and compaction. Skip server-managed variants and other-language examples.',
    competencyIds: ['PYAE-C020'], role: 'core', learningRole: 'reference', purposes: ['conversation-state reference', 'context-window boundary'],
    assignmentPurpose: 'Identify what state the local ConversationManager owns and why older messages eventually need bounded pruning or compaction.',
    whySelected: 'The guide exposes both explicit message history and context-window pressure, providing a current concrete reference without requiring its server-managed path.',
    formatRationale: 'A precise reference is appropriate after prior message-model practice.', alternativeNotes: 'Retained with a strict provider-neutral reading boundary.',
    candidateComparisons: [candidate('Sessions', 'https://openai.github.io/openai-agents-python/sessions/', 'selected separately', 'Better hands-on recent-history practice but less complete on context-window accounting.')],
    judgment: officialJudgment('Supports state ownership and window constraints in C020.', 'The learner annotates which state stays app-owned and which can be compacted.'), rationale: 'Retain as the exact state/window reference.',
  }),
  'PYAE-R-W12-02': makeResourcePlan({
    weekId: 'PYAE-W12', decision: 'retain-repair', title: 'Effective context engineering for AI agents', url: 'https://www.anthropic.com/engineering/effective-context-engineering-for-ai-agents',
    provider: 'Anthropic', format: 'article', estimatedMinutes: 50,
    location: 'Read Context engineering versus prompt engineering through Compaction and Structured note-taking. Stop before subagents. Write a before/after example of raw turns becoming a useful compact note.',
    competencyIds: ['PYAE-C017', 'PYAE-C020'], role: 'core', learningRole: 'learn', purposes: ['context mental model', 'compaction explanation'],
    assignmentPurpose: 'Learn why more history is not automatically better and how compaction can preserve useful facts while discarding low-value detail.',
    whySelected: 'The engineering article explains context selection and compaction conceptually, complementing API documentation with a readable agent-focused mental model.',
    formatRationale: 'Narrative explanation is well suited to a foundational context-engineering concept.', alternativeNotes: 'The assignment excludes advanced multi-agent material.',
    candidateComparisons: [candidate('Conversation state', 'https://developers.openai.com/api/docs/guides/conversation-state', 'selected as reference', 'Precise mechanics but less beginner-oriented as the primary explanation.')],
    judgment: officialJudgment('Directly teaches context quality, compaction, and note preservation for C017/C020.', 'The learner performs a concrete compaction exercise.'), rationale: 'Retain as the primary conceptual explanation.',
  }),
  'PYAE-R-W12-03': makeResourcePlan({
    weekId: 'PYAE-W12', decision: 'retain-promote', title: 'Sessions', url: 'https://openai.github.io/openai-agents-python/sessions/',
    provider: 'OpenAI', format: 'lab', estimatedMinutes: 50,
    location: 'Inspect recent-history limits, SessionSettings, and compaction. Implement an equivalent local list that returns a protected system message plus the latest complete turns; do not install the SDK.',
    competencyIds: ['PYAE-C020'], role: 'core', learningRole: 'practice', purposes: ['bounded-history practice', 'turn-integrity exercise'],
    assignmentPurpose: 'Implement a small local recent-history policy so pruning complete turns is familiar before the full ConversationManager Build.',
    whySelected: 'The page offers a concrete recent-history and compaction pattern that can be recreated locally without adopting the SDK.',
    formatRationale: 'A framework example becomes a guided local practice task.', alternativeNotes: 'Promoted because turn-safe pruning is required by both assessment and Build.',
    candidateComparisons: [candidate('Conversation state', 'https://developers.openai.com/api/docs/guides/conversation-state', 'selected separately', 'Provides reference semantics but less direct practice.')],
    judgment: officialJudgment('Directly practices bounded history for C020.', 'The learner implements and tests complete-turn retention.'), rationale: 'Promote into Core so required pruning behavior is not optional-only.',
  }),

  'PYAE-R-W13-01': makeResourcePlan({
    weekId: 'PYAE-W13', decision: 'retain-repair', title: 'Building effective agents', url: 'https://www.anthropic.com/engineering/building-effective-agents',
    provider: 'Anthropic', format: 'article', estimatedMinutes: 40,
    location: 'Read the Agents section through feedback, checkpoints, stopping conditions, testing, and guardrails. Skip the earlier workflow catalog. Draw the model-tool-observation loop and its exits.',
    competencyIds: ['PYAE-C021'], role: 'core', learningRole: 'learn', purposes: ['agent-loop mental model', 'stopping and guardrails'],
    assignmentPurpose: 'Understand why an agent alternates model decisions with tool feedback and why every loop needs explicit completion and safety exits.',
    whySelected: 'The bounded Agents section explains autonomous feedback loops and control safeguards in accessible engineering language before implementation details.',
    formatRationale: 'A conceptual article is appropriate for the first complete agent-loop mental model.', alternativeNotes: 'Earlier workflow patterns are skipped to keep the assignment focused.',
    candidateComparisons: [candidate('Running agents', 'https://openai.github.io/openai-agents-python/running_agents/', 'selected separately', 'Stronger API-level reference but not as clear as the first conceptual explanation.')],
    judgment: officialJudgment('Directly teaches feedback loops and stopping for C021.', 'The learner draws and annotates every loop exit.'), rationale: 'Retain as the primary agent-loop explanation.',
  }),
  'PYAE-R-W13-02': makeResourcePlan({
    weekId: 'PYAE-W13', decision: 'retain-repair', title: 'Running agents', url: 'https://openai.github.io/openai-agents-python/running_agents/',
    provider: 'OpenAI', format: 'documentation', estimatedMinutes: 45,
    location: 'Read The agent loop, final output, no tool call, and max turns. Trace a provider-neutral state diagram with final-answer, maximum-step, repetition, and error exits; do not install the SDK.',
    competencyIds: ['PYAE-C019', 'PYAE-C021'], role: 'core', learningRole: 'practice', purposes: ['runner lifecycle reference', 'termination cases'],
    assignmentPurpose: 'Trace how a production runner decides whether to dispatch a tool, finish with text, or stop at a configured limit.',
    whySelected: 'The page clearly enumerates loop behavior and terminal conditions that map to the custom AgentRunner without requiring framework adoption.',
    formatRationale: 'A bounded implementation reference follows the conceptual loop article.', alternativeNotes: 'The project remains provider- and SDK-neutral.',
    candidateComparisons: [candidate('Building effective agents', 'https://www.anthropic.com/engineering/building-effective-agents', 'selected as primary', 'Better mental model; this page is kept for explicit runner exits.')],
    judgment: officialJudgment('Supports tool dispatch and termination for C019/C021.', 'The learner traces a full state machine.'), rationale: 'Retain as the explicit runner behavior lesson.',
  }),
  'PYAE-R-W13-03': makeResourcePlan({
    weekId: 'PYAE-W13', decision: 'retain-demote', title: 'Results', url: 'https://openai.github.io/openai-agents-python/results/',
    provider: 'OpenAI', format: 'documentation', estimatedMinutes: 25,
    location: 'Optionally inspect final_output, new_items, and to_input_list, then compare those surfaces with AgentResult and AgentState. No installation is required.',
    competencyIds: ['PYAE-C020', 'PYAE-C021'], role: 'optional', learningRole: 'reference', purposes: ['result-surface reference', 'framework comparison'],
    assignmentPurpose: 'Compare one maintained result object with your app-owned AgentResult after you understand the required loop.',
    whySelected: 'The page is a concise reference for separating final output from newly produced run items, but it is not required to understand or pass the Build.',
    formatRationale: 'Its narrow result-object detail is best used as optional reference.', alternativeNotes: 'Demoted because no assessment or required Build dependency should rely on SDK-specific result fields.',
    candidateComparisons: [candidate('Running agents', 'https://openai.github.io/openai-agents-python/running_agents/', 'selected as core', 'Covers the required lifecycle; Results is narrower enrichment.')],
    judgment: officialJudgment('Provides optional comparison for C020/C021 without carrying required knowledge.', 'The learner may map fields after completing the core design.'), rationale: 'Retain for enrichment but remove from the mandatory path.',
  }),

  'PYAE-R-W14-01': makeResourcePlan({
    weekId: 'PYAE-W14', decision: 'retain-repair', title: 'Writing effective tools for agents', url: 'https://www.anthropic.com/engineering/writing-tools-for-agents',
    provider: 'Anthropic', format: 'article', estimatedMinutes: 45,
    location: 'Read tool boundaries, namespacing, descriptions, returning meaningful context, and token efficiency. Draft read-only and mutating tool descriptions with explicit side effects.',
    competencyIds: ['PYAE-C022', 'PYAE-C023'], role: 'core', learningRole: 'learn', purposes: ['tool-boundary mental model', 'safe contract design'],
    assignmentPurpose: 'Learn to expose narrow tools whose names, inputs, outputs, and side effects are clear enough for both the model and a human reviewer.',
    whySelected: 'The article connects tool ergonomics, context quality, and explicit boundaries in a practical agent-specific explanation.',
    formatRationale: 'A design article is appropriate before implementing filesystem and command safeguards.', alternativeNotes: 'Retained with a concrete drafting activity.',
    candidateComparisons: [candidate('Human-in-the-loop', 'https://openai.github.io/openai-agents-python/human_in_the_loop/', 'selected separately', 'Covers approvals but not general tool contract quality.')],
    judgment: officialJudgment('Directly teaches tool design and authority boundaries for C022/C023.', 'The learner writes and critiques two tool contracts.'), rationale: 'Retain as the safe-tool design foundation.',
  }),
  'PYAE-R-W14-02': makeResourcePlan({
    weekId: 'PYAE-W14', decision: 'replace', title: 'Human-in-the-loop', url: 'https://openai.github.io/openai-agents-python/human_in_the_loop/',
    provider: 'OpenAI', format: 'documentation', estimatedMinutes: 40,
    location: 'Read the overview, Marking tools, the pause-review-approve-or-reject-resume flow, and custom rejection messages. Draw that lifecycle without installing the SDK.',
    competencyIds: ['PYAE-C023'], role: 'core', learningRole: 'learn', purposes: ['approval-gate lifecycle', 'rejection handling'],
    assignmentPurpose: 'Learn how a mutating action pauses before execution, presents reviewable context, and either resumes after approval or stops after rejection.',
    whySelected: 'The current page explicitly models approval interruption, rejection, and resumption, which the Build requires but the redirected generic R2 source did not teach.',
    formatRationale: 'A lifecycle reference plus diagram is enough to teach the gate without adopting the framework.', alternativeNotes: 'Replaces a redirected page whose assigned content no longer matched.',
    candidateComparisons: [candidate('Building effective agents', 'https://www.anthropic.com/engineering/building-effective-agents', 'not selected', 'Mentions guardrails broadly but does not show the approval lifecycle in sufficient detail.')],
    judgment: officialJudgment('Directly teaches HITL approval and rejection for C023.', 'The learner draws the exact pause/review/resume state flow.'), rationale: 'Replace the stale redirect with a directly aligned source.',
  }),
  'PYAE-R-W14-03': makeResourcePlan({
    weekId: 'PYAE-W14', decision: 'replace', title: 'Path Traversal', url: 'https://owasp.org/www-community/attacks/Path_Traversal',
    provider: 'OWASP Foundation', format: 'article', estimatedMinutes: 30,
    location: 'Read the overview, encoded separators, examples, and prevention guidance. Annotate how each malicious path attempts to escape an allowed root.',
    competencyIds: ['PYAE-C006', 'PYAE-C023'], role: 'core', learningRole: 'learn', purposes: ['threat model', 'path-traversal diagnosis'],
    assignmentPurpose: 'Recognize traversal and encoding attacks before implementing a path-confinement boundary.',
    whySelected: 'OWASP supplies concrete attack forms and prevention context that make the risk understandable before the pathlib implementation lab.',
    formatRationale: 'A short threat-focused article establishes why normalization and containment checks are necessary.', alternativeNotes: 'Replaces a broad input-validation page that did not teach the exact filesystem threat.',
    candidateComparisons: [candidate('Input Validation Cheat Sheet', 'https://cheatsheetseries.owasp.org/cheatsheets/Input_Validation_Cheat_Sheet.html', 'rejected', 'Sound but too broad for the specific path-confinement requirement.')],
    judgment: officialJudgment('Directly teaches the filesystem threat behind C006/C023.', 'The learner annotates several escape attempts before coding.'), rationale: 'Replace the generic source with the exact threat model.',
  }),

  'PYAE-R-W15-01': makeResourcePlan({
    weekId: 'PYAE-W15', decision: 'retain-repair', title: 'sqlite3 - DB-API 2.0 interface for SQLite databases', url: 'https://docs.python.org/3/library/sqlite3.html',
    provider: 'Python Software Foundation', format: 'documentation', estimatedMinutes: 80,
    location: 'Complete the tutorial sections for connect, CREATE TABLE, INSERT, SELECT, placeholders, transactions, and connection context managers. Note explicitly that with conn commits or rolls back but does not close conn.',
    competencyIds: ['PYAE-C024'], role: 'core', learningRole: 'reference', purposes: ['SQLite API reference', 'transaction and parameter practice'],
    assignmentPurpose: 'Build a small database with parameterized queries and observe commit, rollback, and connection-lifetime behavior before writing the repository.',
    whySelected: 'The standard-library tutorial documents the exact API used by the Build and corrects a common misconception about connection context managers.',
    formatRationale: 'This API requires an authoritative executable reference.', alternativeNotes: 'Retained with a bounded tutorial and explicit lifecycle warning.',
    candidateComparisons: [candidate('SQLBolt', 'https://sqlbolt.com/', 'selected separately', 'Better for learning relational SQL; sqlite3 remains the precise Python API reference.')],
    judgment: officialJudgment('Directly supports SQLite access, transactions, and safe parameters for C024.', 'The tutorial commands are run against a disposable database.'), rationale: 'Retain as the implementation reference and repair the assigned semantics.',
  }),
  'PYAE-R-W15-02': makeResourcePlan({
    weekId: 'PYAE-W15', decision: 'replace', title: 'SQLBolt - Learn SQL with simple, interactive exercises', url: 'https://sqlbolt.com/',
    provider: 'SQLBolt', format: 'course', estimatedMinutes: 90,
    location: 'Complete Lessons 1, 2, 6, 13, and 16 and every embedded exercise: SELECT, constraints, multi-table creation, INSERT/UPDATE/DELETE, and JOIN. Stop after Lesson 16.',
    competencyIds: ['PYAE-C024'], role: 'core', learningRole: 'learn', purposes: ['relational SQL foundation', 'guided query practice'],
    assignmentPurpose: 'Learn and practice the SQL statements needed to create, relate, write, and query the repository tables.',
    whySelected: 'The interactive lessons teach relational operations incrementally with immediate feedback, a substantially better beginner teacher than the unrelated contextlib reference.',
    formatRationale: 'An interactive course is appropriate for a learner\'s first concentrated SQL work.', alternativeNotes: 'Replaces contextlib, which neither taught database design nor prepared the required repository operations.',
    candidateComparisons: [
      candidate('SQLBolt', 'https://sqlbolt.com/', 'selected', 'Free, incremental, browser-based exercises covering the required SQL subset.'),
      candidate('SQLite SQL Language', 'https://www.sqlite.org/lang.html', 'not selected as primary', 'Authoritative but reference-oriented and too broad for a first lesson.'),
    ],
    judgment: judgment('Short explanations lead directly into visible practice.', 'Teaches the SQL subset required by C024 and the repository Build.', 'Exercises use standard relational operations compatible with SQLite.', 'The public lessons were inspected on 2026-09-09.', 'The selected lessons omit advanced database administration.', 'Every assigned lesson contains immediate interactive exercises.', 'Free in the browser with no mandatory login.'), rationale: 'Replace a non-teaching dependency with the missing SQL foundation.',
  }),
  'PYAE-R-W15-03': makeResourcePlan({
    weekId: 'PYAE-W15', decision: 'retain-repair', title: 'How to use temporary directories and files in tests', url: 'https://docs.pytest.org/en/stable/how-to/tmp_path.html',
    provider: 'pytest', format: 'documentation', estimatedMinutes: 35,
    location: 'Run the tmp_path example. Create a file-backed SQLite database under tmp_path, write and close it, reopen it, assert persistence, then force an exception and assert rollback.',
    competencyIds: ['PYAE-C010', 'PYAE-C011', 'PYAE-C024'], role: 'core', learningRole: 'practice', purposes: ['isolated persistence test', 'restart and rollback proof'],
    assignmentPurpose: 'Practice proving persistence across a real close/reopen cycle while keeping every test isolated and disposable.',
    whySelected: 'The official fixture documentation gives the exact isolated filesystem boundary needed to test durable SQLite behavior rather than only in-memory behavior.',
    formatRationale: 'A runnable fixture lab prepares the acceptance tests directly.', alternativeNotes: 'Retained and strengthened from a generic tmp_path reading into a repository-relevant lab.',
    candidateComparisons: [candidate('TemporaryFileSystem pytest plugins', 'https://pypi.org/', 'rejected', 'An extra dependency is unnecessary for the built-in tmp_path behavior.')],
    judgment: officialJudgment('Directly supports isolated persistence and rollback tests for C010/C011/C024.', 'The learner completes a close/reopen and rollback exercise.'), rationale: 'Retain as required Build practice.',
  }),

  'PYAE-R-W16-01': makeResourcePlan({
    weekId: 'PYAE-W16', decision: 'retain-repair', title: 'Contextual Retrieval', url: 'https://www.anthropic.com/engineering/contextual-retrieval',
    provider: 'Anthropic', format: 'article', estimatedMinutes: 55,
    location: 'Read the RAG overview, the isolated-chunk problem, contextual retrieval, and BM25 sections. Stop before benchmark and cost analysis. Compare one ambiguous chunk before and after adding provenance context.',
    competencyIds: ['PYAE-C025', 'PYAE-C026'], role: 'core', learningRole: 'learn', purposes: ['retrieval mental model', 'chunk-context diagnosis'],
    assignmentPurpose: 'Understand why retrieval needs useful chunks and provenance, and how keyword ranking contributes evidence for a grounded answer.',
    whySelected: 'The article explains retrieval failure caused by context-poor chunks and introduces BM25 in a concrete agent-oriented narrative.',
    formatRationale: 'A visual narrative is a stronger first explanation than an FTS API reference.', alternativeNotes: 'Retained at its current canonical URL and bounded before advanced evaluation/cost sections.',
    candidateComparisons: [candidate('SQLite FTS5', 'https://www.sqlite.org/fts5.html', 'selected separately', 'Authoritative implementation source but not the clearest first RAG explanation.')],
    judgment: officialJudgment('Directly supports chunking, retrieval, and grounding for C025/C026.', 'The learner diagnoses and repairs one ambiguous chunk.'), rationale: 'Retain as the primary conceptual explanation.',
  }),
  'PYAE-R-W16-02': makeResourcePlan({
    weekId: 'PYAE-W16', decision: 'retain-repair', title: 'SQLite FTS5 Extension', url: 'https://www.sqlite.org/fts5.html',
    provider: 'SQLite', format: 'documentation', estimatedMinutes: 50,
    location: 'Read the overview, CREATE VIRTUAL TABLE, MATCH, and bm25 sections. Index three local documents, run parameterized searches, and confirm that lower SQLite bm25() values rank first.',
    competencyIds: ['PYAE-C025', 'PYAE-C026'], role: 'core', learningRole: 'practice', purposes: ['local retrieval practice', 'ranking semantics'],
    assignmentPurpose: 'Build and query a tiny local full-text index so the FTS table, MATCH operator, and score ordering are familiar before the retriever.',
    whySelected: 'The official page precisely documents the SQLite extension used by the Build, including its inverted BM25 score convention.',
    formatRationale: 'A bounded executable reference is appropriate for an exact database extension.', alternativeNotes: 'Retained with an explicit safe parameter and score-ordering exercise.',
    candidateComparisons: [candidate('SQLite FTS3 and FTS4', 'https://www.sqlite.org/fts3.html', 'rejected', 'Older modules do not match the Build\'s FTS5 contract.')],
    judgment: officialJudgment('Directly supports the local retrieval implementation in C024/C026.', 'The learner creates and queries a three-document index.'), rationale: 'Retain as the exact implementation lab.',
  }),
  'PYAE-R-W16-03': makeResourcePlan({
    weekId: 'PYAE-W16', decision: 'replace', title: 'Citation formatting', url: 'https://developers.openai.com/api/docs/guides/citation-formatting',
    provider: 'OpenAI', format: 'documentation', estimatedMinutes: 45,
    location: 'Read Overview, Choose citable units, Represent citable material, and Write effective citation instructions including missing support. Design source blocks for filename and line-range provenance; no API call is required.',
    competencyIds: ['PYAE-C017', 'PYAE-C026'], role: 'core', learningRole: 'learn', purposes: ['citation contract', 'unsupported-answer behavior'],
    assignmentPurpose: 'Learn to package retrieved passages as citable units and instruct the model to distinguish supported answers from missing evidence.',
    whySelected: 'The current guide directly addresses provenance representation and citation instructions, filling a gap left by the stale R2 notebook while remaining usable offline.',
    formatRationale: 'Concrete formatting examples teach the prompt-side contract that the Build assembles.', alternativeNotes: 'The old cookbook notebook was stale/unavailable; a cloud retrieval guide duplicated retrieval rather than teaching provenance.',
    candidateComparisons: [
      candidate('Retrieval', 'https://developers.openai.com/api/docs/guides/retrieval', 'not selected', 'Cloud retrieval would duplicate the local FTS task and add unnecessary provider coupling.'),
      candidate('OpenAI Cookbook RAG notebook', 'https://cookbook.openai.com/', 'rejected', 'The assigned notebook destination was not a stable directly inspectable lesson.'),
    ],
    judgment: officialJudgment('Directly teaches citable context and unsupported-answer instructions for C017/C026.', 'The learner designs the exact source-block format used in the Build.'), rationale: 'Replace the stale notebook with the missing grounding-and-citation lesson.',
  }),
};

export const addedResourcePlans = [
  makeAddedResourcePlan('PYAE-R-W14-04', {
    weekId: 'PYAE-W14', decision: 'add', title: 'pathlib - Object-oriented filesystem paths', url: 'https://docs.python.org/3/library/pathlib.html',
    provider: 'Python Software Foundation', format: 'lab', estimatedMinutes: 45,
    location: 'Read and run Path.resolve, PurePath.is_relative_to, and relative_to examples. Test a safe child, ../ escape, sibling-prefix trap, absolute path, and a symlink when supported.',
    competencyIds: ['PYAE-C006', 'PYAE-C023'], role: 'core', learningRole: 'practice', purposes: ['path-confinement practice', 'normalization edge cases'],
    assignmentPurpose: 'Implement and test the resolved-path containment rule used by the guarded workspace.',
    whySelected: 'The standard-library page documents the exact cross-platform path operations required after OWASP establishes the threat.',
    formatRationale: 'A five-case local lab converts the threat model into an implementable check.', alternativeNotes: 'Added because neither existing resource taught the concrete pathlib containment API.',
    candidateComparisons: [candidate('os.path commonprefix', 'https://docs.python.org/3/library/os.path.html', 'rejected', 'String-prefix operations invite the sibling-prefix bug and are the wrong containment model.')],
    judgment: officialJudgment('Directly teaches the concrete confinement implementation for C006/C023.', 'Five edge cases are executed locally.'), rationale: 'Adds the missing implementation prerequisite.',
  }),
  makeAddedResourcePlan('PYAE-R-W14-05', {
    weekId: 'PYAE-W14', decision: 'add', title: 'subprocess - Subprocess management', url: 'https://docs.python.org/3/library/subprocess.html',
    provider: 'Python Software Foundation', format: 'lab', estimatedMinutes: 35,
    location: 'Read subprocess.run examples, argument sequences, timeout, check, and Security Considerations. Run one harmless success, nonzero exit, and timeout using a list of arguments with shell=False.',
    competencyIds: ['PYAE-C022', 'PYAE-C023'], role: 'core', learningRole: 'practice', purposes: ['safe command invocation', 'failure and timeout handling'],
    assignmentPurpose: 'Practice launching a bounded command without shell-string interpolation and handling its three required outcomes.',
    whySelected: 'The official standard-library page precisely teaches argument-list execution, timeouts, nonzero exits, and shell security for the Build\'s command tool.',
    formatRationale: 'A harmless three-case terminal lab is the shortest safe route to the required behavior.', alternativeNotes: 'Added because execute_command was previously required but not taught.',
    candidateComparisons: [candidate('shlex - shell lexical analysis', 'https://docs.python.org/3/library/shlex.html', 'not selected', 'Useful for shell syntax but unnecessary when the safe interface accepts an argument list.')],
    judgment: officialJudgment('Directly teaches the execute_command API and safety boundary for C023.', 'The learner runs success, failure, and timeout cases.'), rationale: 'Adds the previously hidden command-execution prerequisite.',
  }),
  makeAddedResourcePlan('PYAE-R-W15-04', {
    weekId: 'PYAE-W15', decision: 'add', title: 'PRAGMA user_version', url: 'https://www.sqlite.org/pragma.html#pragma_user_version',
    provider: 'SQLite', format: 'documentation', estimatedMinutes: 20,
    location: 'Read user_version and foreign_keys. Record that user_version is application-owned and foreign-key enforcement is configured per connection.',
    competencyIds: ['PYAE-C024'], role: 'core', learningRole: 'reference', purposes: ['migration-version reference', 'connection-policy reference'],
    assignmentPurpose: 'Learn the two SQLite PRAGMA behaviors the repository uses for migrations and relational integrity.',
    whySelected: 'The primary SQLite reference defines the exact application-owned version integer and connection-level foreign-key switch assessed and used by the Build.',
    formatRationale: 'A short exact reference is appropriate for two API facts.', alternativeNotes: 'Added because these required facts were not covered by the prior Study set.',
    candidateComparisons: [candidate('SQLite PRAGMA statements', 'https://www.sqlite.org/pragma.html', 'selected exact anchor', 'The exact anchors avoid assigning the entire long reference.')],
    judgment: officialJudgment('Directly supports migration and integrity behavior in C024.', 'The learner records and verifies both values in a disposable connection.'), rationale: 'Adds direct teaching for formerly untaught assessed and Build dependencies.',
  }),
  makeAddedResourcePlan('PYAE-R-W15-05', {
    weekId: 'PYAE-W15', decision: 'add', title: 'SQLite Foreign Key Support', url: 'https://www.sqlite.org/foreignkeys.html',
    provider: 'SQLite', format: 'documentation', estimatedMinutes: 25,
    location: 'Read Sections 1 and 2. Create a parent and child table, demonstrate behavior before and after PRAGMA foreign_keys = ON, and keep the enabled state in the connection setup path.',
    competencyIds: ['PYAE-C024'], role: 'core', learningRole: 'reference', purposes: ['relational-integrity reference', 'connection setup check'],
    assignmentPurpose: 'Verify how declared foreign keys become enforced so orphaned sessions, messages, and tool records are rejected.',
    whySelected: 'The official focused page explains both the constraint model and the crucial disabled-by-default compatibility behavior.',
    formatRationale: 'A short primary reference plus a two-state experiment prevents a subtle repository defect.', alternativeNotes: 'Added because schema design requires enforcement, not merely FOREIGN KEY syntax.',
    candidateComparisons: [candidate('SQLBolt JOIN lesson', 'https://sqlbolt.com/lesson/select_queries_with_joins', 'selected separately', 'Teaches relational querying but not SQLite enforcement configuration.')],
    judgment: officialJudgment('Directly supports foreign-key integrity in C024.', 'The learner proves behavior before and after enabling enforcement.'), rationale: 'Adds the missing enforcement prerequisite.',
  }),
];

const optionIds = ['a', 'b', 'c', 'd'];

const questionPatch = (
  id,
  competencyId,
  prompt,
  correctOptionId,
  labels,
  explanation,
) => ({
  id,
  competencyIds: [competencyId],
  prompt,
  options: optionIds.map((optionId, index) => ({ id: optionId, label: labels[index] })),
  correctOptionId,
  explanation,
});

function makeQuestionWeek({
  weekId,
  classification,
  supportingResourceIds,
  priorCompetencyIds,
  patches,
}) {
  const questionIds = Array.from(
    { length: 10 },
    (_, index) => `PYAE-Q-${weekId.slice(-3)}-${String(index + 1).padStart(2, '0')}`,
  );
  const byClass = Object.fromEntries(
    ['A', 'B', 'C', 'D'].map((className) => [
      className,
      questionIds.filter((_, index) => classification[index] === className),
    ]),
  );
  const evidenceBasisByClass = {
    A: 'Each listed answer is explicitly taught or demonstrated by the named Core resource assignment in this week.',
    B: 'Each listed answer relies on a competency explicitly taught and practiced before this week.',
    C: 'Each listed answer is derivable by applying this week\'s taught principles to a small scenario; no new API fact is required.',
    D: 'No final question retains an untaught dependency.',
  };

  return {
    classification,
    finalClassifications: classification,
    supportingResourceIds,
    evidenceBasis: Object.entries(evidenceBasisByClass).map(
      ([className, basis]) => `${className}: ${basis}`,
    ),
    evidenceBasisByClass,
    supportByClass: {
      A: {
        questionIds: byClass.A,
        resourceIds: [...new Set(byClass.A.flatMap((id) => supportingResourceIds[id] ?? []))],
        basis: evidenceBasisByClass.A,
      },
      B: {
        questionIds: byClass.B,
        competencyIds: priorCompetencyIds,
        basis: evidenceBasisByClass.B,
      },
      C: {
        questionIds: byClass.C,
        resourceIds: [...new Set(byClass.C.flatMap((id) => supportingResourceIds[id] ?? []))],
        basis: evidenceBasisByClass.C,
      },
      D: { questionIds: byClass.D, basis: evidenceBasisByClass.D },
    },
    patches,
  };
}

export const questionWeekPlans = {
  'PYAE-W09': makeQuestionWeek({
    weekId: 'PYAE-W09', classification: 'AACACBAABA',
    supportingResourceIds: {
      'PYAE-Q-W09-01': ['PYAE-R-W09-01'], 'PYAE-Q-W09-02': ['PYAE-R-W09-02'],
      'PYAE-Q-W09-03': ['PYAE-R-W09-01'], 'PYAE-Q-W09-04': ['PYAE-R-W09-01', 'PYAE-R-W09-03'],
      'PYAE-Q-W09-05': ['PYAE-R-W09-02'], 'PYAE-Q-W09-06': ['PYAE-R-W09-03'],
      'PYAE-Q-W09-07': ['PYAE-R-W09-02'], 'PYAE-Q-W09-08': ['PYAE-R-W09-01'],
      'PYAE-Q-W09-09': ['PYAE-R-W09-02'], 'PYAE-Q-W09-10': ['PYAE-R-W09-03'],
    },
    priorCompetencyIds: ['PYAE-C010', 'PYAE-C011', 'PYAE-C014'],
    patches: {
      'PYAE-Q-W09-01': questionPatch(
        'PYAE-Q-W09-01', 'PYAE-C014',
        'Which statement best describes structural compatibility with a Python Protocol?', 'b',
        ['A class is compatible only after registering its name with the Protocol.', 'A class is compatible when it provides the required members, even without inheriting from the Protocol.', 'A class is compatible only when every method body is textually identical.', 'A class is compatible whenever its instances compare equal.'],
        'Protocol compatibility is structural: a static type checker compares the required attributes and callable signatures rather than requiring nominal inheritance.',
      ),
      'PYAE-Q-W09-02': questionPatch(
        'PYAE-Q-W09-02', 'PYAE-C016',
        'In the Ollama chat request studied this week, which message role carries persistent behavior instructions rather than a user task or model reply?', 'c',
        ['assistant', 'user', 'system', 'tool'],
        'The system role carries behavior instructions; user and assistant identify conversation turns, while tool identifies a tool result.',
      ),
      'PYAE-Q-W09-03': questionPatch(
        'PYAE-Q-W09-03', 'PYAE-C014',
        'Which decorator permits a Protocol to be used in an isinstance() presence check at runtime?', 'a',
        ['@runtime_checkable', '@final', '@override', '@singledispatch'],
        '@runtime_checkable permits isinstance and issubclass checks for a Protocol, but those checks do not validate complete method signatures.',
      ),
      'PYAE-Q-W09-04': questionPatch(
        'PYAE-Q-W09-04', 'PYAE-C016',
        'Why does the application own a ModelGateway interface instead of passing a provider client throughout its domain code?', 'd',
        ['It makes every provider return byte-for-byte identical text.', 'It removes the need to validate provider responses.', 'It lets domain code bypass all network and timeout failures.', 'It centralizes provider translation and lets tests substitute a deterministic fake.'],
        'An app-owned gateway isolates provider-specific payloads and supplies one seam where a deterministic FakeModel can replace network behavior.',
      ),
      'PYAE-Q-W09-05': questionPatch(
        'PYAE-Q-W09-05', 'PYAE-C016',
        'For a provider that exposes temperature, what change generally makes repeated generations more focused and less varied?', 'a',
        ['Lower the temperature.', 'Increase the context window.', 'Rename the assistant role.', 'Increase the HTTP timeout.'],
        'Temperature changes sampling variability; lowering it generally reduces variation, although it does not by itself guarantee identical output.',
      ),
      'PYAE-Q-W09-06': questionPatch(
        'PYAE-Q-W09-06', 'PYAE-C014',
        'What is the main reason to use FakeModel in the required test path?', 'b',
        ['To estimate the quality of every real provider.', 'To supply controlled responses and inspect calls without network, latency, or API cost.', 'To make production requests run in parallel.', 'To convert every prompt into a training dataset.'],
        'A fake makes model-dependent application behavior deterministic, fast, inspectable, and completely offline.',
      ),
      'PYAE-Q-W09-07': questionPatch(
        'PYAE-Q-W09-07', 'PYAE-C016',
        'What should a provider adapter return to the rest of the application after receiving a provider-specific chat response?', 'a',
        ['An app-owned ModelResponse with the needed text and metadata.', 'The raw HTTP socket so callers can parse it independently.', 'The provider SDK client instance used for the request.', 'A formatted terminal string that discards metadata.'],
        'The adapter translates provider data into the application-owned ModelResponse so downstream code remains provider-neutral.',
      ),
      'PYAE-Q-W09-08': questionPatch(
        'PYAE-Q-W09-08', 'PYAE-C014',
        'A class is passed where ModelGateway is expected but omits generate(). What should a static type checker report?', 'a',
        ['A compatibility error because a required Protocol member is missing.', 'No error because Protocol members are always optional.', 'A runtime HTTP error from the provider.', 'Automatic insertion of a generated generate() method.'],
        'Structural typing still requires every declared member; omission of generate() makes the class incompatible during static checking.',
      ),
      'PYAE-Q-W09-09': questionPatch(
        'PYAE-Q-W09-09', 'PYAE-C016',
        'What does a provider response reason such as "length" communicate to the adapter?', 'b',
        ['The request contained too many message roles.', 'Generation stopped at an output or context limit rather than completing normally.', 'The response was measured in characters rather than tokens.', 'The provider switched to a longer model automatically.'],
        'A length stop reason is a completion-state signal; the adapter should preserve it so the application can distinguish truncation from normal completion.',
      ),
      'PYAE-Q-W09-10': questionPatch(
        'PYAE-Q-W09-10', 'PYAE-C014',
        'How can FakeModel make outgoing prompts inspectable in a unit test?', 'b',
        ['Write every test request to a remote tracing service.', 'Append each received message list to a public calls collection before returning the scripted response.', 'Replace the prompt with a fixed empty string.', 'Read the caller\'s local variables after the test finishes.'],
        'Recording input before returning a scripted response lets tests assert exactly what the application sent without any network call.',
      ),
    },
  }),

  'PYAE-W10': makeQuestionWeek({
    weekId: 'PYAE-W10', classification: 'CAAACBAAAB',
    supportingResourceIds: {
      'PYAE-Q-W10-01': ['PYAE-R-W10-01'], 'PYAE-Q-W10-02': ['PYAE-R-W10-03'],
      'PYAE-Q-W10-03': ['PYAE-R-W10-02', 'PYAE-R-W10-03'], 'PYAE-Q-W10-04': ['PYAE-R-W10-01', 'PYAE-R-W10-02'],
      'PYAE-Q-W10-05': ['PYAE-R-W10-02', 'PYAE-R-W10-03'], 'PYAE-Q-W10-06': [],
      'PYAE-Q-W10-07': ['PYAE-R-W10-01'], 'PYAE-Q-W10-08': ['PYAE-R-W10-03'],
      'PYAE-Q-W10-09': ['PYAE-R-W10-01'], 'PYAE-Q-W10-10': [],
    },
    priorCompetencyIds: ['PYAE-C014', 'PYAE-C012'],
    patches: {
      'PYAE-Q-W10-01': questionPatch(
        'PYAE-Q-W10-01', 'PYAE-C017',
        'Which prompt outline gives a structured extraction task the clearest usable contract?', 'b',
        ['Persona, greeting, joke, signature, and model name.', 'Task, input context, constraints, output schema, and a representative example.', 'Temperature, timeout, API key, provider logo, and billing tier.', 'Question, answer, apology, citation count, and random seed.'],
        'A useful extraction contract states the task, delimits the input, supplies constraints and the output schema, and demonstrates the intended shape.',
      ),
      'PYAE-Q-W10-02': questionPatch(
        'PYAE-Q-W10-02', 'PYAE-C018',
        'Which exception does Pydantic raise when parsed input does not satisfy a model?', 'a',
        ['ValidationError', 'JSONDecodeError in every case', 'SchemaRetry', 'ModelMismatchWarning'],
        'Pydantic collects model validation problems in ValidationError; malformed JSON may be represented within that validation failure when using model_validate_json().',
      ),
      'PYAE-Q-W10-03': questionPatch(
        'PYAE-Q-W10-03', 'PYAE-C018',
        'Why can syntactically valid JSON still be unusable to TaskExtraction?', 'd',
        ['JSON cannot contain strings.', 'Pydantic accepts only Python dictionaries, never JSON text.', 'Valid JSON always satisfies every application rule.', 'Its fields or values may violate the Pydantic schema or a business constraint.'],
        'JSON syntax validity is separate from schema and business validity; the application must validate both boundaries.',
      ),
      'PYAE-Q-W10-04': questionPatch(
        'PYAE-Q-W10-04', 'PYAE-C017',
        'Which approach most strongly constrains a capable model to the application\'s declared output shape?', 'c',
        ['Ask politely for no extra prose but accept any response.', 'Strip the first and last line regardless of their content.', 'Use schema-constrained structured output and still validate the returned value locally.', 'Increase temperature until the response looks like JSON.'],
        'Schema-constrained output reduces format drift, while local validation remains the application\'s final trust boundary.',
      ),
      'PYAE-Q-W10-05': questionPatch(
        'PYAE-Q-W10-05', 'PYAE-C018',
        'What feedback is most useful in one bounded schema-repair attempt?', 'c',
        ['Only the word "wrong".', 'A new unrelated example with no mention of the failure.', 'The invalid output, concise validation errors, and the unchanged required schema.', 'The complete application source tree and every prior conversation.'],
        'A repair request should preserve the contract and give specific actionable errors without adding unrelated context.',
      ),
      'PYAE-Q-W10-06': questionPatch(
        'PYAE-Q-W10-06', 'PYAE-C018',
        'In Pydantic v2, which method returns a model instance as a standard Python dictionary?', 'b',
        ['model_json_schema()', 'model_dump()', 'model_validate_json()', 'model_copy_json()'],
        'model_dump() serializes a model instance to a Python dictionary; model_json_schema() describes the model rather than an instance.',
      ),
      'PYAE-Q-W10-07': questionPatch(
        'PYAE-Q-W10-07', 'PYAE-C017',
        'What does a few-shot section contribute to a prompt contract?', 'b',
        ['It retries the same provider request indefinitely.', 'It shows a small number of representative input/output examples.', 'It removes the need to specify an output schema.', 'It trains and permanently changes the underlying model.'],
        'Few-shot prompting places a small set of examples in context to demonstrate how the stated contract should be applied.',
      ),
      'PYAE-Q-W10-08': questionPatch(
        'PYAE-Q-W10-08', 'PYAE-C018',
        'Which call both parses raw JSON text and validates it as TaskExtraction in the assigned Pydantic workflow?', 'd',
        ['TaskExtraction.model_dump(raw)', 'json.dumps(TaskExtraction)', 'TaskExtraction.model_json_schema(raw)', 'TaskExtraction.model_validate_json(raw)'],
        'model_validate_json() parses JSON text and validates the resulting values against the model in one explicit boundary.',
      ),
      'PYAE-Q-W10-09': questionPatch(
        'PYAE-Q-W10-09', 'PYAE-C017',
        'Why should untrusted user text be placed inside explicit delimiters rather than concatenated into instruction prose?', 'a',
        ['It makes the boundary between application instructions and user-supplied content clearer.', 'It guarantees the model will never make an error.', 'It encrypts the user text before transmission.', 'It automatically converts the input to a Pydantic model.'],
        'Delimiters make the intended data boundary visible; they reduce ambiguity but do not replace validation or security controls.',
      ),
      'PYAE-Q-W10-10': questionPatch(
        'PYAE-Q-W10-10', 'PYAE-C018',
        'Why must the extraction repair loop enforce a small maximum retry count?', 'b',
        ['A second request always produces the same token sequence.', 'An unbounded loop can consume time or money and never reach a valid result.', 'Pydantic permits validation only twice per process.', 'JSON becomes invalid after three parse attempts.'],
        'A bounded retry policy guarantees termination and gives the caller a clear failure state when repair does not succeed.',
      ),
    },
  }),

  'PYAE-W11': makeQuestionWeek({
    weekId: 'PYAE-W11', classification: 'AAAABAAACA',
    supportingResourceIds: {
      'PYAE-Q-W11-01': ['PYAE-R-W11-01'], 'PYAE-Q-W11-02': ['PYAE-R-W11-01'],
      'PYAE-Q-W11-03': ['PYAE-R-W11-01', 'PYAE-R-W11-02'], 'PYAE-Q-W11-04': ['PYAE-R-W11-01', 'PYAE-R-W11-02'],
      'PYAE-Q-W11-05': [], 'PYAE-Q-W11-06': ['PYAE-R-W11-03'],
      'PYAE-Q-W11-07': ['PYAE-R-W11-02'], 'PYAE-Q-W11-08': ['PYAE-R-W11-01'],
      'PYAE-Q-W11-09': ['PYAE-R-W11-01', 'PYAE-R-W11-02'], 'PYAE-Q-W11-10': ['PYAE-R-W11-01'],
    },
    priorCompetencyIds: ['PYAE-C018'],
    patches: {
      'PYAE-Q-W11-01': questionPatch(
        'PYAE-Q-W11-01', 'PYAE-C019',
        'Which provider tool declaration shape identifies a callable function and contains its name, description, and parameter schema?', 'a',
        ['{"type":"function","function":{"name":"...","description":"...","parameters":{...}}}', '{"role":"tool","content":{"python":"..."}}', '{"callable":true,"handler":"memory address"}', '{"type":"message","schema":"free text"}'],
        'The provider-facing declaration identifies a function tool and nests its model-visible name, description, and JSON Schema parameters.',
      ),
      'PYAE-Q-W11-02': questionPatch(
        'PYAE-Q-W11-02', 'PYAE-C018',
        'How do function-call arguments cross the model/application boundary in the format studied this week?', 'b',
        ['As a live Python dictionary that can be trusted immediately.', 'As JSON text that the application must parse and validate before dispatch.', 'As positional command-line arguments only.', 'As an already executed Python function result.'],
        'The model proposes JSON-encoded arguments; application code owns parsing, schema validation, authorization, and execution.',
      ),
      'PYAE-Q-W11-03': questionPatch(
        'PYAE-Q-W11-03', 'PYAE-C019',
        'Why should the dispatcher convert an expected tool exception into a structured ToolResult?', 'd',
        ['So every failed tool is reported as success.', 'So the dispatcher can discard the tool name.', 'So the handler can bypass argument validation next time.', 'So the runner receives a controlled failure observation instead of crashing with an unhandled exception.'],
        'Exception containment preserves the runner boundary and provides an inspectable failure that callers or the next model turn can handle.',
      ),
      'PYAE-Q-W11-04': questionPatch(
        'PYAE-Q-W11-04', 'PYAE-C019',
        'What is the model-facing purpose of a tool parameter description?', 'b',
        ['It stores the Python handler object.', 'It explains the parameter meaning and constraints so the model can form an appropriate call.', 'It grants operating-system permission to the tool.', 'It replaces the JSON Schema type declaration.'],
        'Descriptions add semantic guidance; types and validation still enforce the machine-readable contract.',
      ),
      'PYAE-Q-W11-05': questionPatch(
        'PYAE-Q-W11-05', 'PYAE-C018',
        'The model supplies malformed JSON in a tool call. What should dispatch do first?', 'a',
        ['Reject it as a structured invalid-arguments result without invoking the handler.', 'Repair it with eval() and invoke the handler.', 'Pass the raw text into every registered tool.', 'Silently replace it with an empty object and report success.'],
        'Parsing and validation must succeed before dispatch; malformed input is a controlled boundary failure and must not reach the handler.',
      ),
      'PYAE-Q-W11-06': questionPatch(
        'PYAE-Q-W11-06', 'PYAE-C019',
        'Which standard-library module exposes signature(), Parameter, and argument binding for Python callables?', 'c',
        ['functools', 'types', 'inspect', 'operator'],
        'inspect.signature() exposes parameters, annotations, defaults, and bind operations used by introspection-based tooling.',
      ),
      'PYAE-Q-W11-07': questionPatch(
        'PYAE-Q-W11-07', 'PYAE-C019',
        'Why must a tool registry never execute model-provided Python text with unrestricted eval() or exec()?', 'd',
        ['It prevents JSON serialization of normal tool results.', 'It makes function descriptions too short.', 'It allows only read-only expressions.', 'It grants arbitrary code execution outside the registry\'s named, validated tool boundary.'],
        'Unrestricted dynamic execution bypasses the registry contract and can perform any action available to the process.',
      ),
      'PYAE-Q-W11-08': questionPatch(
        'PYAE-Q-W11-08', 'PYAE-C018',
        'Where does JSON Schema list property names that callers must supply?', 'c',
        ['In the title string.', 'Inside additionalProperties as values.', 'In the top-level required array for that object schema.', 'In the description of the function tool.'],
        'Object schemas declare properties separately and name mandatory ones in the required array.',
      ),
      'PYAE-Q-W11-09': questionPatch(
        'PYAE-Q-W11-09', 'PYAE-C019',
        'A tool returns a 50 MB document. What is the safest dispatcher behavior before adding an observation to model context?', 'b',
        ['Append all bytes because more context is always safer.', 'Apply an explicit size policy: reject or return a bounded summary/reference with truncation metadata.', 'Delete the registered tool permanently.', 'Retry the same tool until its output becomes smaller.'],
        'A bounded output policy protects memory and context limits while making any truncation or external reference explicit.',
      ),
      'PYAE-Q-W11-10': questionPatch(
        'PYAE-Q-W11-10', 'PYAE-C018',
        'Which field connects a returned tool-result message to the model\'s original requested call?', 'a',
        ['tool_call_id', 'schema_version', 'assistant_name', 'dispatch_index'],
        'The tool result carries the original tool_call_id so the next request preserves the relationship between request and observation.',
      ),
    },
  }),

  'PYAE-W12': makeQuestionWeek({
    weekId: 'PYAE-W12', classification: 'AACBAAAAAB',
    supportingResourceIds: {
      'PYAE-Q-W12-01': ['PYAE-R-W12-01'], 'PYAE-Q-W12-02': ['PYAE-R-W12-01', 'PYAE-R-W12-03'],
      'PYAE-Q-W12-03': ['PYAE-R-W12-01'], 'PYAE-Q-W12-04': [],
      'PYAE-Q-W12-05': ['PYAE-R-W12-02', 'PYAE-R-W12-03'], 'PYAE-Q-W12-06': ['PYAE-R-W12-02'],
      'PYAE-Q-W12-07': ['PYAE-R-W12-03'], 'PYAE-Q-W12-08': ['PYAE-R-W12-01'],
      'PYAE-Q-W12-09': ['PYAE-R-W12-02', 'PYAE-R-W12-03'], 'PYAE-Q-W12-10': [],
    },
    priorCompetencyIds: ['PYAE-C016', 'PYAE-C018', 'PYAE-C019'],
    patches: {
      'PYAE-Q-W12-01': questionPatch(
        'PYAE-Q-W12-01', 'PYAE-C020',
        'What should ConversationManager do before sending a request whose estimated prompt exceeds its configured context budget?', 'a',
        ['Prune or compact according to policy and return a clear failure if the protected content still cannot fit.', 'Send it unchanged and assume the provider silently removes safe messages.', 'Delete the system instructions first.', 'Split every individual word into a separate request.'],
        'Budget enforcement belongs before the request; protected content stays pinned and an impossible budget becomes an explicit failure.',
      ),
      'PYAE-Q-W12-02': questionPatch(
        'PYAE-Q-W12-02', 'PYAE-C017',
        'Why is the system instruction normally protected during history pruning?', 'b',
        ['It always contains the shortest message.', 'It defines the agent\'s persistent behavior and safety boundary for the remaining turns.', 'Providers charge no tokens for system text.', 'It can reconstruct every removed tool result automatically.'],
        'Removing persistent instructions can change behavior and safety expectations even when the recent dialogue remains intact.',
      ),
      'PYAE-Q-W12-03': questionPatch(
        'PYAE-Q-W12-03', 'PYAE-C020',
        'A lightweight estimator uses roughly one token per four English characters. What should the developer conclude about that value?', 'c',
        ['It exactly matches every provider tokenizer.', 'It counts output tokens but never input tokens.', 'It is a planning estimate that needs a safety buffer, not an exact tokenizer result.', 'It is valid only for JSON and invalid for prose.'],
        'Character ratios are rough budgeting heuristics; language, content, and tokenizer differ, so the manager reserves headroom.',
      ),
      'PYAE-Q-W12-04': questionPatch(
        'PYAE-Q-W12-04', 'PYAE-C020',
        'If pruning removes an assistant message that requested a tool, what should happen to its matching tool result?', 'd',
        ['Keep only the tool result because it is newer.', 'Convert the tool result into a system instruction.', 'Change its tool_call_id to an unrelated retained call.', 'Remove the request and result together as one coherent interaction.'],
        'Tool requests and their results form a linked interaction; retaining one without the other produces invalid or misleading history.',
      ),
      'PYAE-Q-W12-05': questionPatch(
        'PYAE-Q-W12-05', 'PYAE-C020',
        'Which technique preserves useful facts from old turns while reducing the raw history sent to the model?', 'a',
        ['Replace selected old turns with a bounded compaction summary.', 'Duplicate every old turn at the front of the prompt.', 'Rename all old messages as system instructions.', 'Store only token counts and discard every fact.'],
        'Compaction condenses relevant facts and decisions while permitting low-value raw dialogue to leave the active context.',
      ),
      'PYAE-Q-W12-06': questionPatch(
        'PYAE-Q-W12-06', 'PYAE-C017',
        'Why can adding large amounts of irrelevant context reduce answer quality?', 'b',
        ['The model permanently forgets its training data.', 'Relevant instructions and evidence become harder to attend to among distracting material.', 'Every long prompt is converted into an image.', 'The provider automatically changes the user\'s question.'],
        'Context engineering selects useful information; irrelevant volume can distract from the evidence and instructions that matter.',
      ),
      'PYAE-Q-W12-07': questionPatch(
        'PYAE-Q-W12-07', 'PYAE-C020',
        'After protected messages, which history should a sliding-window policy normally evict first?', 'c',
        ['The newest incomplete message regardless of role.', 'Every tool message across the entire conversation.', 'The oldest complete, non-protected turn or interaction.', 'The system instruction followed by the current user goal.'],
        'Oldest complete interactions are the safest first eviction candidates because the policy preserves protected and most recent context.',
      ),
      'PYAE-Q-W12-08': questionPatch(
        'PYAE-Q-W12-08', 'PYAE-C020',
        'Why must the input budget leave room below the model\'s total context-window limit?', 'd',
        ['To make database writes faster.', 'To force every answer to one sentence.', 'To reserve space for additional system prompts from unrelated apps.', 'To allow the model\'s output and absorb estimation error without exceeding the limit.'],
        'The context limit covers input and generated output, and approximate estimators require additional safety margin.',
      ),
      'PYAE-Q-W12-09': questionPatch(
        'PYAE-Q-W12-09', 'PYAE-C017',
        'Which compaction summary is most useful for the next agent turn?', 'b',
        ['A list of how many characters each removed message contained.', 'A concise record of durable facts, decisions, unresolved work, and relevant tool outcomes.', 'A verbatim copy of every removed message.', 'A generic sentence saying that a conversation occurred.'],
        'Useful compaction preserves information needed for future reasoning rather than merely shortening text.',
      ),
      'PYAE-Q-W12-10': questionPatch(
        'PYAE-Q-W12-10', 'PYAE-C020',
        'What is the most robust local representation for conversation state before adapting it to a provider request?', 'a',
        ['An ordered collection of app-owned typed messages with stable roles and tool-call links.', 'One repeatedly concatenated string with no message boundaries.', 'Only the most recent assistant response.', 'The provider client object itself.'],
        'App-owned typed messages preserve ordering and relationships while adapters remain responsible for provider-specific serialization.',
      ),
    },
  }),
};
